#!/usr/bin/env node
/**
 * render_email.mjs — render templates/event-invitation.tsx to HTML and plain text.
 *
 *   node scripts/render_email.mjs [--dossier artifacts/dossier.json] [--event artifacts/event.json]
 *
 * Props come from the dossier and the event brief. A prop with no evidence behind it is
 * omitted, and the template's own guard drops that section rather than rendering a gap.
 * Both outputs are written: some clients show the text part, and an autogenerated one
 * reads as broken.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? dflt : process.argv[i + 1];
};
const read = async (p) => JSON.parse(await readFile(resolve(p), "utf8"));

const dossier = await read(arg("dossier", "artifacts/dossier.json"));
const event = await read(arg("event", "artifacts/event.json"));
const f = (name) => dossier.required_fields?.[name]?.value ?? null;

const props = {
  recipientFirstName: String(dossier.name ?? "").split(" ")[0] || null,
  eventName: event.event_name ?? null,
  eventDate: event.date ?? null,
  eventCity: event.city ?? null,
  eventVenue: event.venue ?? undefined,
  reason: dossier.outreach?.reason_to_engage ?? null,
  reasonSourceUrl: dossier.outreach?.reason_source_url ?? undefined,
  audienceLine: event.description ?? null,
  rsvpUrl: event.event_url ?? null,
  senderName: (event.hosts ?? [])[0] ?? null,
  senderTitle: "Host",
  communityName: event.series_context ? "VC Village" : "VC Village",
  unsubscribeUrl: event.unsubscribe_url ?? "",
  previewText: dossier.outreach?.preview_text ?? null,
};

const missing = ["recipientFirstName", "eventName", "eventDate", "eventCity", "reason", "rsvpUrl", "previewText"]
  .filter((k) => !props[k]);
if (missing.length) {
  console.error(`Cannot render: ${missing.join(", ")} not populated. Fill them in step 4 first.`);
  process.exit(2);
}

let render;
try {
  ({ render } = await import("@react-email/render"));
} catch {
  console.error("@react-email/render is not installed. Run: npm i -D @react-email/render react react-dom");
  process.exit(3);
}
const { default: EventInvitation } = await import("../templates/event-invitation.js").catch(() => ({}));
if (!EventInvitation) {
  console.error("Compile templates/event-invitation.tsx first (tsx/esbuild), then re-run.");
  process.exit(3);
}

await mkdir(resolve("artifacts"), { recursive: true });
const el = EventInvitation(props);
const html = await render(el);
const text = await render(el, { plainText: true });
await writeFile(resolve("artifacts/invitation.html"), html);
await writeFile(resolve("artifacts/invitation.txt"), text);
await writeFile(resolve("artifacts/invitation.props.json"),
  JSON.stringify({ props, subject: dossier.outreach?.subject ?? null,
                   review_state: "hold", send_state: "draft_only_not_sent" }, null, 2) + "\n");
console.log(`artifacts/invitation.html  ${html.length} bytes`);
console.log(`artifacts/invitation.txt   ${text.length} bytes`);
console.log(`subject: ${dossier.outreach?.subject ?? "(unset)"}`);
console.log("review_state: hold · send_state: draft_only_not_sent");
